#!/usr/bin/env bash
# print "Best School" 10 times using a while loop

counter=10

while [ "$counter" -gt 0 ]
do
	echo "Best School"
	if [ "$counter" -eq 2 ]
	then
		echo "Hi"
	fi
	counter=$(( counter - 1 ))
done
