#!/bin/bash
# print some stuffs

counter=1
while [ $counter -le 20 ]
do
    case $counter in
        4)
		echo "4"
		echo "and bad luck from China"
		;;
        9)
		echo "9"
		echo "and bad luck from Japan"
		;;
        17)
		echo "17"
		echo "and bad luck from Italy"
		;;
        *) echo $counter;;
    esac
    ((counter++))
done
